// Bindings generated by `windows-bindgen` 0.62.1

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

pub mod Microsoft {
    pub mod Graphics {
        pub mod Imaging {
            windows_core::imp::define_interface!(
                IImageBuffer,
                IImageBuffer_Vtbl,
                0x3baabd0b_1854_51f1_bd2a_74c87858f461
            );
            impl windows_core::RuntimeType for IImageBuffer {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::for_interface::<Self>();
            }
            #[repr(C)]
            #[doc(hidden)]
            pub struct IImageBuffer_Vtbl {
                pub base__: windows_core::IInspectable_Vtbl,
                pub Buffer: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    *mut *mut core::ffi::c_void,
                ) -> windows_core::HRESULT,
                pub PixelFormat: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    *mut ImageBufferPixelFormat,
                )
                    -> windows_core::HRESULT,
                pub PixelHeight: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    *mut i32,
                )
                    -> windows_core::HRESULT,
                pub PixelWidth: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    *mut i32,
                ) -> windows_core::HRESULT,
                pub RowStride: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    *mut i32,
                ) -> windows_core::HRESULT,
                pub CopyToByteArray: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    u32,
                    *mut u8,
                )
                    -> windows_core::HRESULT,
                pub CopyToSoftwareBitmap: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    *mut *mut core::ffi::c_void,
                )
                    -> windows_core::HRESULT,
            }
            windows_core::imp::define_interface!(
                IImageBufferStatics,
                IImageBufferStatics_Vtbl,
                0x35b17bd3_f346_529f_8c0f_3bf96c56eb13
            );
            impl windows_core::RuntimeType for IImageBufferStatics {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::for_interface::<Self>();
            }
            #[repr(C)]
            #[doc(hidden)]
            pub struct IImageBufferStatics_Vtbl {
                pub base__: windows_core::IInspectable_Vtbl,
                pub CreateForBuffer: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    *mut core::ffi::c_void,
                    ImageBufferPixelFormat,
                    i32,
                    i32,
                    i32,
                    *mut *mut core::ffi::c_void,
                )
                    -> windows_core::HRESULT,
                pub CreateForSoftwareBitmap: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    *mut core::ffi::c_void,
                    *mut *mut core::ffi::c_void,
                )
                    -> windows_core::HRESULT,
            }
            #[repr(transparent)]
            #[derive(Clone, Debug, Eq, PartialEq)]
            pub struct ImageBuffer(windows_core::IUnknown);
            windows_core::imp::interface_hierarchy!(
                ImageBuffer,
                windows_core::IUnknown,
                windows_core::IInspectable
            );
            windows_core::imp::required_hierarchy!(ImageBuffer, windows::Foundation::IClosable);
            impl ImageBuffer {
                pub fn Close(&self) -> windows_core::Result<()> {
                    let this =
                        &windows_core::Interface::cast::<windows::Foundation::IClosable>(self)?;
                    unsafe {
                        (windows_core::Interface::vtable(this).Close)(
                            windows_core::Interface::as_raw(this),
                        )
                        .ok()
                    }
                }
                pub fn Buffer(&self) -> windows_core::Result<windows::Storage::Streams::IBuffer> {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).Buffer)(
                            windows_core::Interface::as_raw(this),
                            &mut result__,
                        )
                        .and_then(|| windows_core::Type::from_abi(result__))
                    }
                }
                pub fn PixelFormat(&self) -> windows_core::Result<ImageBufferPixelFormat> {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).PixelFormat)(
                            windows_core::Interface::as_raw(this),
                            &mut result__,
                        )
                        .map(|| result__)
                    }
                }
                pub fn PixelHeight(&self) -> windows_core::Result<i32> {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).PixelHeight)(
                            windows_core::Interface::as_raw(this),
                            &mut result__,
                        )
                        .map(|| result__)
                    }
                }
                pub fn PixelWidth(&self) -> windows_core::Result<i32> {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).PixelWidth)(
                            windows_core::Interface::as_raw(this),
                            &mut result__,
                        )
                        .map(|| result__)
                    }
                }
                pub fn RowStride(&self) -> windows_core::Result<i32> {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).RowStride)(
                            windows_core::Interface::as_raw(this),
                            &mut result__,
                        )
                        .map(|| result__)
                    }
                }
                pub fn CopyToByteArray(&self, values: &mut [u8]) -> windows_core::Result<()> {
                    let this = self;
                    unsafe {
                        (windows_core::Interface::vtable(this).CopyToByteArray)(
                            windows_core::Interface::as_raw(this),
                            values.len().try_into().unwrap(),
                            values.as_mut_ptr(),
                        )
                        .ok()
                    }
                }
                pub fn CopyToSoftwareBitmap(
                    &self,
                ) -> windows_core::Result<windows::Graphics::Imaging::SoftwareBitmap>
                {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).CopyToSoftwareBitmap)(
                            windows_core::Interface::as_raw(this),
                            &mut result__,
                        )
                        .and_then(|| windows_core::Type::from_abi(result__))
                    }
                }
                pub fn CreateForBuffer<P0>(
                    buffer: P0,
                    pixelformat: ImageBufferPixelFormat,
                    width: i32,
                    height: i32,
                    rowstride: i32,
                ) -> windows_core::Result<ImageBuffer>
                where
                    P0: windows_core::Param<windows::Storage::Streams::IBuffer>,
                {
                    Self::IImageBufferStatics(|this| unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).CreateForBuffer)(
                            windows_core::Interface::as_raw(this),
                            buffer.param().abi(),
                            pixelformat,
                            width,
                            height,
                            rowstride,
                            &mut result__,
                        )
                        .and_then(|| windows_core::Type::from_abi(result__))
                    })
                }
                pub fn CreateForSoftwareBitmap<P0>(
                    softwarebitmap: P0,
                ) -> windows_core::Result<ImageBuffer>
                where
                    P0: windows_core::Param<windows::Graphics::Imaging::SoftwareBitmap>,
                {
                    Self::IImageBufferStatics(|this| unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).CreateForSoftwareBitmap)(
                            windows_core::Interface::as_raw(this),
                            softwarebitmap.param().abi(),
                            &mut result__,
                        )
                        .and_then(|| windows_core::Type::from_abi(result__))
                    })
                }
                fn IImageBufferStatics<
                    R,
                    F: FnOnce(&IImageBufferStatics) -> windows_core::Result<R>,
                >(
                    callback: F,
                ) -> windows_core::Result<R> {
                    static SHARED: windows_core::imp::FactoryCache<
                        ImageBuffer,
                        IImageBufferStatics,
                    > = windows_core::imp::FactoryCache::new();
                    SHARED.call(callback)
                }
            }
            impl windows_core::RuntimeType for ImageBuffer {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::for_class::<Self, IImageBuffer>();
            }
            unsafe impl windows_core::Interface for ImageBuffer {
                type Vtable = <IImageBuffer as windows_core::Interface>::Vtable;
                const IID: windows_core::GUID = <IImageBuffer as windows_core::Interface>::IID;
            }
            impl windows_core::RuntimeName for ImageBuffer {
                const NAME: &'static str = "Microsoft.Graphics.Imaging.ImageBuffer";
            }
            unsafe impl Send for ImageBuffer {}
            unsafe impl Sync for ImageBuffer {}
            #[repr(transparent)]
            #[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
            pub struct ImageBufferPixelFormat(pub i32);
            impl ImageBufferPixelFormat {
                pub const Rgb8: Self = Self(137224i32);
                pub const Rgba8: Self = Self(30i32);
                pub const Argb8: Self = Self(2498570i32);
                pub const Bgra8: Self = Self(87i32);
                pub const Gray8: Self = Self(62i32);
            }
            impl windows_core::TypeKind for ImageBufferPixelFormat {
                type TypeKind = windows_core::CopyType;
            }
            impl windows_core::RuntimeType for ImageBufferPixelFormat {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::from_slice(
                        b"enum(Microsoft.Graphics.Imaging.ImageBufferPixelFormat;i4)",
                    );
            }
        }
    }
    pub mod Windows {
        pub mod AI {
            #[repr(transparent)]
            #[derive(Clone, Debug, Eq, PartialEq)]
            pub struct AIFeatureReadyResult(windows_core::IUnknown);
            windows_core::imp::interface_hierarchy!(
                AIFeatureReadyResult,
                windows_core::IUnknown,
                windows_core::IInspectable
            );
            impl AIFeatureReadyResult {
                pub fn Error(&self) -> windows_core::Result<windows_core::HRESULT> {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).Error)(
                            windows_core::Interface::as_raw(this),
                            &mut result__,
                        )
                        .map(|| result__)
                    }
                }
                pub fn ErrorDisplayText(&self) -> windows_core::Result<windows_core::HSTRING> {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).ErrorDisplayText)(
                            windows_core::Interface::as_raw(this),
                            &mut result__,
                        )
                        .map(|| core::mem::transmute(result__))
                    }
                }
                pub fn ExtendedError(&self) -> windows_core::Result<windows_core::HRESULT> {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).ExtendedError)(
                            windows_core::Interface::as_raw(this),
                            &mut result__,
                        )
                        .map(|| result__)
                    }
                }
                pub fn Status(&self) -> windows_core::Result<AIFeatureReadyResultState> {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).Status)(
                            windows_core::Interface::as_raw(this),
                            &mut result__,
                        )
                        .map(|| result__)
                    }
                }
                pub fn PackageInstallationFailed(&self) -> windows_core::Result<bool> {
                    let this = &windows_core::Interface::cast::<IAIFeatureReadyResult2>(self)?;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).PackageInstallationFailed)(
                            windows_core::Interface::as_raw(this),
                            &mut result__,
                        )
                        .map(|| result__)
                    }
                }
            }
            impl windows_core::RuntimeType for AIFeatureReadyResult {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::for_class::<Self, IAIFeatureReadyResult>();
            }
            unsafe impl windows_core::Interface for AIFeatureReadyResult {
                type Vtable = <IAIFeatureReadyResult as windows_core::Interface>::Vtable;
                const IID: windows_core::GUID =
                    <IAIFeatureReadyResult as windows_core::Interface>::IID;
            }
            impl windows_core::RuntimeName for AIFeatureReadyResult {
                const NAME: &'static str = "Microsoft.Windows.AI.AIFeatureReadyResult";
            }
            unsafe impl Send for AIFeatureReadyResult {}
            unsafe impl Sync for AIFeatureReadyResult {}
            #[repr(transparent)]
            #[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
            pub struct AIFeatureReadyResultState(pub i32);
            impl AIFeatureReadyResultState {
                pub const InProgress: Self = Self(0i32);
                pub const Success: Self = Self(1i32);
                pub const Failure: Self = Self(2i32);
            }
            impl windows_core::TypeKind for AIFeatureReadyResultState {
                type TypeKind = windows_core::CopyType;
            }
            impl windows_core::RuntimeType for AIFeatureReadyResultState {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::from_slice(
                        b"enum(Microsoft.Windows.AI.AIFeatureReadyResultState;i4)",
                    );
            }
            #[repr(transparent)]
            #[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
            pub struct AIFeatureReadyState(pub i32);
            impl AIFeatureReadyState {
                pub const Ready: Self = Self(0i32);
                pub const NotReady: Self = Self(1i32);
                pub const NotSupportedOnCurrentSystem: Self = Self(2i32);
                pub const DisabledByUser: Self = Self(3i32);
            }
            impl windows_core::TypeKind for AIFeatureReadyState {
                type TypeKind = windows_core::CopyType;
            }
            impl windows_core::RuntimeType for AIFeatureReadyState {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::from_slice(
                        b"enum(Microsoft.Windows.AI.AIFeatureReadyState;i4)",
                    );
            }
            windows_core::imp::define_interface!(
                IAIFeatureReadyResult,
                IAIFeatureReadyResult_Vtbl,
                0x936a78a6_c242_5937_9814_e512d4193a6d
            );
            impl windows_core::RuntimeType for IAIFeatureReadyResult {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::for_interface::<Self>();
            }
            #[repr(C)]
            #[doc(hidden)]
            pub struct IAIFeatureReadyResult_Vtbl {
                pub base__: windows_core::IInspectable_Vtbl,
                pub Error: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    *mut windows_core::HRESULT,
                ) -> windows_core::HRESULT,
                pub ErrorDisplayText: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    *mut *mut core::ffi::c_void,
                )
                    -> windows_core::HRESULT,
                pub ExtendedError: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    *mut windows_core::HRESULT,
                )
                    -> windows_core::HRESULT,
                pub Status: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    *mut AIFeatureReadyResultState,
                ) -> windows_core::HRESULT,
            }
            windows_core::imp::define_interface!(
                IAIFeatureReadyResult2,
                IAIFeatureReadyResult2_Vtbl,
                0xec5f1d67_43c1_5bdb_b9f4_a0c7110582cb
            );
            impl windows_core::RuntimeType for IAIFeatureReadyResult2 {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::for_interface::<Self>();
            }
            #[repr(C)]
            #[doc(hidden)]
            pub struct IAIFeatureReadyResult2_Vtbl {
                pub base__: windows_core::IInspectable_Vtbl,
                pub PackageInstallationFailed: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    *mut bool,
                )
                    -> windows_core::HRESULT,
            }
            pub mod Imaging {
                windows_core::imp::define_interface!(
                    IRecognizedLine,
                    IRecognizedLine_Vtbl,
                    0x612a6be6_f6bb_53c9_84ce_f0a5e565faa7
                );
                impl windows_core::RuntimeType for IRecognizedLine {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_interface::<Self>();
                }
                #[repr(C)]
                #[doc(hidden)]
                pub struct IRecognizedLine_Vtbl {
                    pub base__: windows_core::IInspectable_Vtbl,
                    pub Text: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut *mut core::ffi::c_void,
                    )
                        -> windows_core::HRESULT,
                    pub BoundingBox: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut RecognizedTextBoundingBox,
                    )
                        -> windows_core::HRESULT,
                    pub Words: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut u32,
                        *mut *mut *mut core::ffi::c_void,
                    )
                        -> windows_core::HRESULT,
                    pub Style: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut RecognizedLineStyle,
                    )
                        -> windows_core::HRESULT,
                    pub LineStyleConfidence: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut f32,
                    )
                        -> windows_core::HRESULT,
                }
                windows_core::imp::define_interface!(
                    IRecognizedText,
                    IRecognizedText_Vtbl,
                    0xae4766d3_2924_57a6_b3d3_b866f59b9972
                );
                impl windows_core::RuntimeType for IRecognizedText {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_interface::<Self>();
                }
                #[repr(C)]
                #[doc(hidden)]
                pub struct IRecognizedText_Vtbl {
                    pub base__: windows_core::IInspectable_Vtbl,
                    pub Lines: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut u32,
                        *mut *mut *mut core::ffi::c_void,
                    )
                        -> windows_core::HRESULT,
                    pub TextAngle: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut f32,
                    )
                        -> windows_core::HRESULT,
                }
                windows_core::imp::define_interface!(
                    IRecognizedWord,
                    IRecognizedWord_Vtbl,
                    0x6b53daab_3410_5088_826a_0788a1ee3b52
                );
                impl windows_core::RuntimeType for IRecognizedWord {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_interface::<Self>();
                }
                #[repr(C)]
                #[doc(hidden)]
                pub struct IRecognizedWord_Vtbl {
                    pub base__: windows_core::IInspectable_Vtbl,
                    pub Text: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut *mut core::ffi::c_void,
                    )
                        -> windows_core::HRESULT,
                    pub BoundingBox: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut RecognizedTextBoundingBox,
                    )
                        -> windows_core::HRESULT,
                    pub MatchConfidence: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut f32,
                    )
                        -> windows_core::HRESULT,
                }
                windows_core::imp::define_interface!(
                    ITextRecognizer,
                    ITextRecognizer_Vtbl,
                    0xbe7bf6c0_30f6_570d_bd92_3ffe5665d933
                );
                impl windows_core::RuntimeType for ITextRecognizer {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_interface::<Self>();
                }
                #[repr(C)]
                #[doc(hidden)]
                pub struct ITextRecognizer_Vtbl {
                    pub base__: windows_core::IInspectable_Vtbl,
                    pub RecognizeTextFromImageAsync:
                        unsafe extern "system" fn(
                            *mut core::ffi::c_void,
                            *mut core::ffi::c_void,
                            *mut *mut core::ffi::c_void,
                        ) -> windows_core::HRESULT,
                    pub RecognizeTextFromImage: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut core::ffi::c_void,
                        *mut *mut core::ffi::c_void,
                    )
                        -> windows_core::HRESULT,
                }
                windows_core::imp::define_interface!(
                    ITextRecognizerStatics,
                    ITextRecognizerStatics_Vtbl,
                    0x3788c2fd_e496_53ab_85a7_e54a135824e9
                );
                impl windows_core::RuntimeType for ITextRecognizerStatics {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_interface::<Self>();
                }
                #[repr(C)]
                #[doc(hidden)]
                pub struct ITextRecognizerStatics_Vtbl {
                    pub base__: windows_core::IInspectable_Vtbl,
                    pub GetReadyState: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut super::AIFeatureReadyState,
                    )
                        -> windows_core::HRESULT,
                    pub EnsureReadyAsync: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut *mut core::ffi::c_void,
                    )
                        -> windows_core::HRESULT,
                    pub CreateAsync: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut *mut core::ffi::c_void,
                    )
                        -> windows_core::HRESULT,
                }
                #[repr(transparent)]
                #[derive(Clone, Debug, Eq, PartialEq)]
                pub struct RecognizedLine(windows_core::IUnknown);
                windows_core::imp::interface_hierarchy!(
                    RecognizedLine,
                    windows_core::IUnknown,
                    windows_core::IInspectable
                );
                impl RecognizedLine {
                    pub fn Text(&self) -> windows_core::Result<windows_core::HSTRING> {
                        let this = self;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).Text)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| core::mem::transmute(result__))
                        }
                    }
                    pub fn BoundingBox(&self) -> windows_core::Result<RecognizedTextBoundingBox> {
                        let this = self;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).BoundingBox)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        }
                    }
                    pub fn Words(
                        &self,
                    ) -> windows_core::Result<windows_core::Array<RecognizedWord>>
                    {
                        let this = self;
                        unsafe {
                            let mut result__ = core::mem::MaybeUninit::zeroed();
                            (windows_core::Interface::vtable(this).Words)(
                                windows_core::Interface::as_raw(this),
                                windows_core::Array::<RecognizedWord>::set_abi_len(
                                    core::mem::transmute(&mut result__),
                                ),
                                result__.as_mut_ptr() as *mut _ as _,
                            )
                            .map(|| result__.assume_init())
                        }
                    }
                    pub fn Style(&self) -> windows_core::Result<RecognizedLineStyle> {
                        let this = self;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).Style)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        }
                    }
                    pub fn LineStyleConfidence(&self) -> windows_core::Result<f32> {
                        let this = self;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).LineStyleConfidence)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        }
                    }
                }
                impl windows_core::RuntimeType for RecognizedLine {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_class::<Self, IRecognizedLine>();
                }
                unsafe impl windows_core::Interface for RecognizedLine {
                    type Vtable = <IRecognizedLine as windows_core::Interface>::Vtable;
                    const IID: windows_core::GUID =
                        <IRecognizedLine as windows_core::Interface>::IID;
                }
                impl windows_core::RuntimeName for RecognizedLine {
                    const NAME: &'static str = "Microsoft.Windows.AI.Imaging.RecognizedLine";
                }
                unsafe impl Send for RecognizedLine {}
                unsafe impl Sync for RecognizedLine {}
                #[repr(transparent)]
                #[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
                pub struct RecognizedLineStyle(pub i32);
                impl RecognizedLineStyle {
                    pub const Handwritten: Self = Self(0i32);
                }
                impl windows_core::TypeKind for RecognizedLineStyle {
                    type TypeKind = windows_core::CopyType;
                }
                impl windows_core::RuntimeType for RecognizedLineStyle {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::from_slice(
                            b"enum(Microsoft.Windows.AI.Imaging.RecognizedLineStyle;i4)",
                        );
                }
                #[repr(transparent)]
                #[derive(Clone, Debug, Eq, PartialEq)]
                pub struct RecognizedText(windows_core::IUnknown);
                windows_core::imp::interface_hierarchy!(
                    RecognizedText,
                    windows_core::IUnknown,
                    windows_core::IInspectable
                );
                impl RecognizedText {
                    pub fn Lines(
                        &self,
                    ) -> windows_core::Result<windows_core::Array<RecognizedLine>>
                    {
                        let this = self;
                        unsafe {
                            let mut result__ = core::mem::MaybeUninit::zeroed();
                            (windows_core::Interface::vtable(this).Lines)(
                                windows_core::Interface::as_raw(this),
                                windows_core::Array::<RecognizedLine>::set_abi_len(
                                    core::mem::transmute(&mut result__),
                                ),
                                result__.as_mut_ptr() as *mut _ as _,
                            )
                            .map(|| result__.assume_init())
                        }
                    }
                    pub fn TextAngle(&self) -> windows_core::Result<f32> {
                        let this = self;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).TextAngle)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        }
                    }
                }
                impl windows_core::RuntimeType for RecognizedText {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_class::<Self, IRecognizedText>();
                }
                unsafe impl windows_core::Interface for RecognizedText {
                    type Vtable = <IRecognizedText as windows_core::Interface>::Vtable;
                    const IID: windows_core::GUID =
                        <IRecognizedText as windows_core::Interface>::IID;
                }
                impl windows_core::RuntimeName for RecognizedText {
                    const NAME: &'static str = "Microsoft.Windows.AI.Imaging.RecognizedText";
                }
                unsafe impl Send for RecognizedText {}
                unsafe impl Sync for RecognizedText {}
                #[repr(C)]
                #[derive(Clone, Copy, Debug, Default, PartialEq)]
                pub struct RecognizedTextBoundingBox {
                    pub BottomLeft: windows::Foundation::Point,
                    pub BottomRight: windows::Foundation::Point,
                    pub TopLeft: windows::Foundation::Point,
                    pub TopRight: windows::Foundation::Point,
                }
                impl windows_core::TypeKind for RecognizedTextBoundingBox {
                    type TypeKind = windows_core::CopyType;
                }
                impl windows_core::RuntimeType for RecognizedTextBoundingBox {
                    const SIGNATURE :windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice ( b"struct(Microsoft.Windows.AI.Imaging.RecognizedTextBoundingBox;struct(Windows.Foundation.Point;f4;f4);struct(Windows.Foundation.Point;f4;f4);struct(Windows.Foundation.Point;f4;f4);struct(Windows.Foundation.Point;f4;f4))" ) ;
                }
                #[repr(transparent)]
                #[derive(Clone, Debug, Eq, PartialEq)]
                pub struct RecognizedWord(windows_core::IUnknown);
                windows_core::imp::interface_hierarchy!(
                    RecognizedWord,
                    windows_core::IUnknown,
                    windows_core::IInspectable
                );
                impl RecognizedWord {
                    pub fn Text(&self) -> windows_core::Result<windows_core::HSTRING> {
                        let this = self;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).Text)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| core::mem::transmute(result__))
                        }
                    }
                    pub fn BoundingBox(&self) -> windows_core::Result<RecognizedTextBoundingBox> {
                        let this = self;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).BoundingBox)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        }
                    }
                    pub fn MatchConfidence(&self) -> windows_core::Result<f32> {
                        let this = self;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).MatchConfidence)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        }
                    }
                }
                impl windows_core::RuntimeType for RecognizedWord {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_class::<Self, IRecognizedWord>();
                }
                unsafe impl windows_core::Interface for RecognizedWord {
                    type Vtable = <IRecognizedWord as windows_core::Interface>::Vtable;
                    const IID: windows_core::GUID =
                        <IRecognizedWord as windows_core::Interface>::IID;
                }
                impl windows_core::RuntimeName for RecognizedWord {
                    const NAME: &'static str = "Microsoft.Windows.AI.Imaging.RecognizedWord";
                }
                unsafe impl Send for RecognizedWord {}
                unsafe impl Sync for RecognizedWord {}
                #[repr(transparent)]
                #[derive(Clone, Debug, Eq, PartialEq)]
                pub struct TextRecognizer(windows_core::IUnknown);
                windows_core::imp::interface_hierarchy!(
                    TextRecognizer,
                    windows_core::IUnknown,
                    windows_core::IInspectable
                );
                windows_core::imp::required_hierarchy!(
                    TextRecognizer,
                    windows::Foundation::IClosable
                );
                impl TextRecognizer {
                    pub fn Close(&self) -> windows_core::Result<()> {
                        let this =
                            &windows_core::Interface::cast::<windows::Foundation::IClosable>(self)?;
                        unsafe {
                            (windows_core::Interface::vtable(this).Close)(
                                windows_core::Interface::as_raw(this),
                            )
                            .ok()
                        }
                    }
                    pub fn RecognizeTextFromImageAsync<P0>(
                        &self,
                        imagebuffer: P0,
                    ) -> windows_core::Result<windows_future::IAsyncOperation<RecognizedText>>
                    where
                        P0: windows_core::Param<super::super::super::Graphics::Imaging::ImageBuffer>,
                    {
                        let this = self;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).RecognizeTextFromImageAsync)(
                                windows_core::Interface::as_raw(this),
                                imagebuffer.param().abi(),
                                &mut result__,
                            )
                            .and_then(|| windows_core::Type::from_abi(result__))
                        }
                    }
                    pub fn RecognizeTextFromImage<P0>(
                        &self,
                        imagebuffer: P0,
                    ) -> windows_core::Result<RecognizedText>
                    where
                        P0: windows_core::Param<super::super::super::Graphics::Imaging::ImageBuffer>,
                    {
                        let this = self;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).RecognizeTextFromImage)(
                                windows_core::Interface::as_raw(this),
                                imagebuffer.param().abi(),
                                &mut result__,
                            )
                            .and_then(|| windows_core::Type::from_abi(result__))
                        }
                    }
                    pub fn GetReadyState() -> windows_core::Result<super::AIFeatureReadyState> {
                        Self::ITextRecognizerStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).GetReadyState)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        })
                    }
                    pub fn EnsureReadyAsync() -> windows_core::Result<
                        windows_future::IAsyncOperationWithProgress<
                            super::AIFeatureReadyResult,
                            f64,
                        >,
                    > {
                        Self::ITextRecognizerStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).EnsureReadyAsync)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .and_then(|| windows_core::Type::from_abi(result__))
                        })
                    }
                    pub fn CreateAsync()
                    -> windows_core::Result<windows_future::IAsyncOperation<TextRecognizer>>
                    {
                        Self::ITextRecognizerStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).CreateAsync)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .and_then(|| windows_core::Type::from_abi(result__))
                        })
                    }
                    fn ITextRecognizerStatics<
                        R,
                        F: FnOnce(&ITextRecognizerStatics) -> windows_core::Result<R>,
                    >(
                        callback: F,
                    ) -> windows_core::Result<R> {
                        static SHARED: windows_core::imp::FactoryCache<
                            TextRecognizer,
                            ITextRecognizerStatics,
                        > = windows_core::imp::FactoryCache::new();
                        SHARED.call(callback)
                    }
                }
                impl windows_core::RuntimeType for TextRecognizer {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_class::<Self, ITextRecognizer>();
                }
                unsafe impl windows_core::Interface for TextRecognizer {
                    type Vtable = <ITextRecognizer as windows_core::Interface>::Vtable;
                    const IID: windows_core::GUID =
                        <ITextRecognizer as windows_core::Interface>::IID;
                }
                impl windows_core::RuntimeName for TextRecognizer {
                    const NAME: &'static str = "Microsoft.Windows.AI.Imaging.TextRecognizer";
                }
                unsafe impl Send for TextRecognizer {}
                unsafe impl Sync for TextRecognizer {}
            }
        }
    }
}
