import { Palette } from "std-widgets.slint";

export component StatusBar inherits Rectangle {
    in property <string> status-text: "就绪";
    in property <int> status-level: 0;

    height: 22px;
    background: Palette.alternate-background;

    HorizontalLayout {
        padding-left: 7px;
        padding-right: 7px;
        spacing: 6px;

        status-indicator := Rectangle {
            width: 12px;

            if root.status-level == 2: Text {
                text: "×";
                color: #cf222e;
                font-size: 17px;
                font-weight: 700;
                horizontal-alignment: center;
                vertical-alignment: center;
            }
            if root.status-level != 2: Text {
                text: "√";
                color: root.status-level == 1 ? #238636 : Palette.alternate-foreground;
                font-size: 15px;
                font-weight: 700;
                horizontal-alignment: center;
                vertical-alignment: center;
            }
        }
        Text {
            text: root.status-text;
            color: root.status-level == 2 ? #cf222e : Palette.foreground;
            font-size: 13px;
            vertical-alignment: center;
            overflow: elide;
        }
    }

    Tooltip { text: @markdown("\{root.status-text}"); }
}
